/**
 * Server Side Rendering
 */
import { APIGatewayEvent } from "aws-lambda";
import * as React from "react";
import { renderToString } from "react-dom/server";

import App from "../App";
import ConfigContext from "../components/ConfigContext";
import config from "./config";
import html from "./html";
import { Stats } from "./types";
import { QueryClient, QueryClientProvider } from "react-query";
import { ReactQueryDevtools } from "react-query/devtools";

const queryClient = new QueryClient();
/**
 * Server-side rendering
 */
export default async function render(_event: APIGatewayEvent): Promise<string> {
  // The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
  const stats = (await import("../../dist/stats.json")) as unknown as Stats;
  const content = renderToString(
    <React.StrictMode>
      <ConfigContext.Provider value={config}>
        <QueryClientProvider client={queryClient} contextSharing>
          <App />
          <ReactQueryDevtools/>
        </QueryClientProvider>
      </ConfigContext.Provider>
    </React.StrictMode>
    ,
  );
  return html({ stats, content, config });
}
